[2025-09-21T11:21:11.999+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:21:12.001+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:21:12.050+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:21:12.052+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:21:12.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:20:00+00:00 [queued]>
[2025-09-21T11:21:12.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:20:00+00:00 [queued]>
[2025-09-21T11:21:12.145+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:21:12.172+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:20:00+00:00
[2025-09-21T11:21:12.192+0000] {standard_task_runner.py:57} INFO - Started process 696 to run task
[2025-09-21T11:21:12.197+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:20:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpvyphysu7']
[2025-09-21T11:21:12.201+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask validate_model_performance
[2025-09-21T11:21:12.283+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:21:12.283+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:20:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:21:12.285+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:20:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:21:12.393+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:20:00+00:00'
[2025-09-21T11:21:12.445+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 1048468.0468730413, 'rmse': 1023.9472871554674, 'mae': 838.6074634128147, 'r2': 0.8959967678399292}
[2025-09-21T11:21:12.477+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T112000, start_date=20250921T112112, end_date=20250921T112112
[2025-09-21T11:21:12.530+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:21:12.555+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
