[2025-08-03T10:44:08.465+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509
[2025-08-03T10:44:08.466+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance'
[2025-08-03T10:44:08.509+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509
[2025-08-03T10:44:08.511+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance'
[2025-08-03T10:44:08.558+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-08-03T10:43:00+00:00 [queued]>
[2025-08-03T10:44:08.572+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-08-03T10:43:00+00:00 [queued]>
[2025-08-03T10:44:08.573+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:44:08.592+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-08-03 10:43:00+00:00
[2025-08-03T10:44:08.606+0000] {standard_task_runner.py:57} INFO - Started process 751 to run task
[2025-08-03T10:44:08.611+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-08-03T10:43:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpwh77cc9l']
[2025-08-03T10:44:08.615+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask validate_model_performance
[2025-08-03T10:44:08.683+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509
[2025-08-03T10:44:08.683+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:43:00+00:00/task_id=validate_model_performance'
[2025-08-03T10:44:08.686+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-08-03T10:43:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:44:08.796+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:43:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:43:00+00:00'
[2025-08-03T10:44:08.834+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 1151493.6435049437, 'rmse': 1073.0767183687026, 'mae': 879.3096847799089, 'r2': 0.9182604870619855}
[2025-08-03T10:44:08.866+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250803T104300, start_date=20250803T104408, end_date=20250803T104408
[2025-08-03T10:44:08.905+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:44:08.927+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
