[2025-09-21T11:13:01.597+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:13:01.598+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:13:01.651+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:13:01.652+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:13:01.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:12:00+00:00 [queued]>
[2025-09-21T11:13:01.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:12:00+00:00 [queued]>
[2025-09-21T11:13:01.738+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:13:01.758+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-09-21 11:12:00+00:00
[2025-09-21T11:13:01.772+0000] {standard_task_runner.py:57} INFO - Started process 447 to run task
[2025-09-21T11:13:01.778+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-09-21T11:12:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpjk72wry2']
[2025-09-21T11:13:01.783+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask fetch_training_data
[2025-09-21T11:13:01.904+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:13:01.905+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:12:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:13:01.909+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:12:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:13:02.099+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:12:00+00:00'
[2025-09-21T11:13:02.118+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-09-21T11:13:03.684+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100519  155959    452  ...    product_A 2025-09-21 11:12:16.069285
100520  155960    460  ...    product_A 2025-09-21 11:12:26.082879
100521  155961    462  ...    product_A 2025-09-21 11:12:36.441146
100522  155962    463  ...    product_A 2025-09-21 11:12:46.458591
100523  155963    464  ...    product_A 2025-09-21 11:12:56.474671

[5 rows x 12 columns]
[2025-09-21T11:13:03.767+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-06-23', 'end_date': '2025-09-21'}
[2025-09-21T11:13:03.831+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250921T111200, start_date=20250921T111301, end_date=20250921T111303
[2025-09-21T11:13:03.960+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:13:04.007+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
