[2025-09-21T11:07:50.113+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:07:50.114+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:07:50.659+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:07:50.661+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:07:50.746+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:04:00+00:00 [queued]>
[2025-09-21T11:07:50.761+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:04:00+00:00 [queued]>
[2025-09-21T11:07:50.762+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-09-21T11:07:50.791+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-09-21 11:04:00+00:00
[2025-09-21T11:07:50.811+0000] {standard_task_runner.py:57} INFO - Started process 276 to run task
[2025-09-21T11:07:50.818+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-09-21T11:04:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmplmdmb1lt']
[2025-09-21T11:07:50.824+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask fetch_training_data
[2025-09-21T11:07:51.004+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:07:51.006+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:04:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:07:51.013+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:04:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:07:51.240+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:04:00+00:00'
[2025-09-21T11:07:51.259+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-09-21T11:07:53.550+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100489  155929    430  ...    product_A 2025-09-21 11:07:15.564625
100490  155930    431  ...    product_A 2025-09-21 11:07:16.545768
100491  155931    432  ...    product_A 2025-09-21 11:07:26.765075
100492  155932    426  ...    product_A 2025-09-21 11:07:36.734997
100493  155933    486  ...    product_A 2025-09-21 11:07:48.583266

[5 rows x 12 columns]
[2025-09-21T11:07:53.646+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-06-23', 'end_date': '2025-09-21'}
[2025-09-21T11:07:53.835+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250921T110400, start_date=20250921T110750, end_date=20250921T110753
[2025-09-21T11:07:53.921+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:07:53.963+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
