[2025-09-21T12:07:42.855+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:07:42.856+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:07:42.893+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:07:42.894+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:07:42.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:48:00+00:00 [queued]>
[2025-09-21T12:07:42.948+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:48:00+00:00 [queued]>
[2025-09-21T12:07:42.949+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T12:07:43.000+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:48:00+00:00
[2025-09-21T12:07:43.010+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2025-09-21T12:07:43.014+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:48:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpdcdlh12b']
[2025-09-21T12:07:43.018+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask validate_model_performance
[2025-09-21T12:07:43.141+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:07:43.141+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:48:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:07:43.143+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:48:00+00:00 [running]> on host 6d4fbafceae4
[2025-09-21T12:07:43.403+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:48:00+00:00'
[2025-09-21T12:07:44.788+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 829331.2847809666, 'rmse': 910.6762788065618, 'mae': 733.0880705180921, 'r2': 0.7748873190615873}
[2025-09-21T12:07:44.820+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T114800, start_date=20250921T120742, end_date=20250921T120744
[2025-09-21T12:07:44.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T12:07:44.901+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
