[2025-09-21T11:35:12.987+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:35:12.988+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:35:13.047+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:35:13.051+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:35:13.123+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:34:00+00:00 [queued]>
[2025-09-21T11:35:13.135+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:34:00+00:00 [queued]>
[2025-09-21T11:35:13.136+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:35:13.162+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:34:00+00:00
[2025-09-21T11:35:13.177+0000] {standard_task_runner.py:57} INFO - Started process 1133 to run task
[2025-09-21T11:35:13.182+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:34:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpf788mmn9']
[2025-09-21T11:35:13.188+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask validate_model_performance
[2025-09-21T11:35:13.299+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:35:13.300+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:34:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:35:13.305+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:34:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:35:13.550+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:34:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:34:00+00:00'
[2025-09-21T11:35:13.623+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 1502447.2407818453, 'rmse': 1225.7435460902273, 'mae': 907.6721240149604, 'r2': 0.8606261451615977}
[2025-09-21T11:35:13.678+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T113400, start_date=20250921T113513, end_date=20250921T113513
[2025-09-21T11:35:13.758+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:35:13.803+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
