[2025-09-21T11:43:11.746+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:43:11.747+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:43:11.791+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:43:11.794+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:43:11.854+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:42:00+00:00 [queued]>
[2025-09-21T11:43:11.865+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:42:00+00:00 [queued]>
[2025-09-21T11:43:11.866+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:43:11.883+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:42:00+00:00
[2025-09-21T11:43:11.896+0000] {standard_task_runner.py:57} INFO - Started process 1370 to run task
[2025-09-21T11:43:11.900+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:42:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp79dmpp4l']
[2025-09-21T11:43:11.904+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask validate_model_performance
[2025-09-21T11:43:11.976+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:43:11.977+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:42:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:43:11.979+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:42:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:43:12.096+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:42:00+00:00'
[2025-09-21T11:43:12.150+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 1081997.1299262766, 'rmse': 1040.1909103266942, 'mae': 817.3808162477281, 'r2': 0.9329955708557083}
[2025-09-21T11:43:12.196+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T114200, start_date=20250921T114311, end_date=20250921T114312
[2025-09-21T11:43:12.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:43:12.252+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
