[2025-08-03T10:36:01.375+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:36:01.375+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:36:01.412+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:36:01.413+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:36:01.452+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:35:00+00:00 [queued]>
[2025-08-03T10:36:01.462+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:35:00+00:00 [queued]>
[2025-08-03T10:36:01.463+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:36:01.479+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:35:00+00:00
[2025-08-03T10:36:01.489+0000] {standard_task_runner.py:57} INFO - Started process 489 to run task
[2025-08-03T10:36:01.494+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:35:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp3xyerity']
[2025-08-03T10:36:01.498+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask fetch_training_data
[2025-08-03T10:36:01.563+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:36:01.564+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:35:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:36:01.567+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:35:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:36:01.667+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:35:00+00:00'
[2025-08-03T10:36:01.679+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:36:02.589+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100546  155986    462  ...    product_A 2025-08-03 10:35:21.600731
100547  155987    463  ...    product_A 2025-08-03 10:35:31.446542
100548  155988    464  ...    product_A 2025-08-03 10:35:41.463893
100549  155989    465  ...    product_A 2025-08-03 10:35:51.480747
100550  155990    466  ...    product_A 2025-08-03 10:36:01.266672

[5 rows x 12 columns]
[2025-08-03T10:36:02.617+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:36:02.647+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T103500, start_date=20250803T103601, end_date=20250803T103602
[2025-08-03T10:36:02.716+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:36:02.748+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
