[2025-08-03T10:39:01.173+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:39:01.174+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:39:01.211+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:39:01.212+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:39:01.250+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:38:00+00:00 [queued]>
[2025-08-03T10:39:01.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:38:00+00:00 [queued]>
[2025-08-03T10:39:01.261+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:39:01.278+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:38:00+00:00
[2025-08-03T10:39:01.288+0000] {standard_task_runner.py:57} INFO - Started process 582 to run task
[2025-08-03T10:39:01.293+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:38:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp_54zdm8d']
[2025-08-03T10:39:01.297+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask fetch_training_data
[2025-08-03T10:39:01.361+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:39:01.362+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:38:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:39:01.365+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:38:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:39:01.467+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:38:00+00:00'
[2025-08-03T10:39:01.479+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:39:02.446+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100564  156004     92  ...    product_A 2025-08-03 10:38:20.655887
100565  156005     91  ...    product_A 2025-08-03 10:38:30.439036
100566  156006     90  ...    product_A 2025-08-03 10:38:40.454405
100567  156007     89  ...    product_A 2025-08-03 10:38:50.467135
100568  156008     88  ...    product_A 2025-08-03 10:39:00.281803

[5 rows x 12 columns]
[2025-08-03T10:39:02.474+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:39:02.505+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T103800, start_date=20250803T103901, end_date=20250803T103902
[2025-08-03T10:39:02.553+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:39:02.586+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
