[2025-09-21T11:08:25.515+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:08:25.516+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:08:25.606+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:08:25.664+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:08:25.856+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:06:00+00:00 [queued]>
[2025-09-21T11:08:25.875+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:06:00+00:00 [queued]>
[2025-09-21T11:08:25.881+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:08:25.922+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:06:00+00:00
[2025-09-21T11:08:25.944+0000] {standard_task_runner.py:57} INFO - Started process 306 to run task
[2025-09-21T11:08:25.951+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:06:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmplurgqayd']
[2025-09-21T11:08:25.960+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask validate_model_performance
[2025-09-21T11:08:26.070+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:08:26.074+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:06:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:08:26.086+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:06:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:08:26.249+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:06:00+00:00'
[2025-09-21T11:08:33.435+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 840546.5943688372, 'rmse': 916.8132821730045, 'mae': 801.1260952419705, 'r2': 0.8767890759049677}
[2025-09-21T11:08:33.481+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T110600, start_date=20250921T110825, end_date=20250921T110833
[2025-09-21T11:08:33.545+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:08:33.569+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
