[2025-09-21T11:16:01.667+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:16:01.668+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:16:01.710+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:16:01.712+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:16:01.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:15:00+00:00 [queued]>
[2025-09-21T11:16:01.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:15:00+00:00 [queued]>
[2025-09-21T11:16:01.771+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:16:01.797+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-09-21 11:15:00+00:00
[2025-09-21T11:16:01.809+0000] {standard_task_runner.py:57} INFO - Started process 534 to run task
[2025-09-21T11:16:01.813+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-09-21T11:15:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpcgbyhjgj']
[2025-09-21T11:16:01.817+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask fetch_training_data
[2025-09-21T11:16:01.907+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:16:01.908+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:15:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:16:01.912+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:15:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:16:02.553+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:15:00+00:00'
[2025-09-21T11:16:02.565+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-09-21T11:16:04.190+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100537  155977     94  ...    product_A 2025-09-21 11:15:20.951040
100538  155978     93  ...    product_A 2025-09-21 11:15:30.965593
100539  155979     92  ...    product_A 2025-09-21 11:15:41.308809
100540  155980     91  ...    product_A 2025-09-21 11:15:51.329908
100541  155981     90  ...    product_A 2025-09-21 11:16:01.344382

[5 rows x 12 columns]
[2025-09-21T11:16:04.259+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-06-23', 'end_date': '2025-09-21'}
[2025-09-21T11:16:04.309+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250921T111500, start_date=20250921T111601, end_date=20250921T111604
[2025-09-21T11:16:04.413+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:16:04.467+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
