[2025-08-03T10:51:01.162+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:51:01.163+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:51:01.203+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:51:01.204+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:51:01.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:50:00+00:00 [queued]>
[2025-08-03T10:51:01.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:50:00+00:00 [queued]>
[2025-08-03T10:51:01.257+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:51:01.273+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:50:00+00:00
[2025-08-03T10:51:01.282+0000] {standard_task_runner.py:57} INFO - Started process 960 to run task
[2025-08-03T10:51:01.287+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:50:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpk13orso5']
[2025-08-03T10:51:01.291+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask fetch_training_data
[2025-08-03T10:51:01.359+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:51:01.359+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:50:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:51:01.362+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:50:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:51:01.476+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:50:00+00:00'
[2025-08-03T10:51:01.487+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:51:02.443+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100636  156076     20  ...    product_A 2025-08-03 10:50:16.728325
100637  156077     19  ...    product_A 2025-08-03 10:50:26.742806
100638  156078     18  ...    product_A 2025-08-03 10:50:36.756916
100639  156079     17  ...    product_A 2025-08-03 10:50:46.590474
100640  156080     16  ...    product_A 2025-08-03 10:50:56.604719

[5 rows x 12 columns]
[2025-08-03T10:51:02.474+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:51:02.508+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T105000, start_date=20250803T105101, end_date=20250803T105102
[2025-08-03T10:51:02.590+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:51:02.624+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
