[2025-08-03T10:48:01.116+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:48:01.117+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:48:01.156+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:48:01.157+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:48:01.197+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:47:00+00:00 [queued]>
[2025-08-03T10:48:01.208+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:47:00+00:00 [queued]>
[2025-08-03T10:48:01.209+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-03T10:48:01.225+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-08-03 10:47:00+00:00
[2025-08-03T10:48:01.236+0000] {standard_task_runner.py:57} INFO - Started process 864 to run task
[2025-08-03T10:48:01.240+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-08-03T10:47:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp9oaix2_n']
[2025-08-03T10:48:01.244+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask fetch_training_data
[2025-08-03T10:48:01.309+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509
[2025-08-03T10:48:01.310+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-08-03T10:47:00+00:00/task_id=fetch_training_data'
[2025-08-03T10:48:01.313+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-08-03T10:47:00+00:00 [running]> on host 407839faddcf
[2025-08-03T10:48:01.415+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T10:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T10:47:00+00:00'
[2025-08-03T10:48:01.428+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-08-03T10:48:02.379+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100618  156058    116  ...    product_A 2025-08-03 10:47:17.774344
100619  156059    117  ...    product_A 2025-08-03 10:47:27.606522
100620  156060    118  ...    product_A 2025-08-03 10:47:37.621464
100621  156061    112  ...    product_A 2025-08-03 10:47:47.447314
100622  156062     69  ...    product_A 2025-08-03 10:47:57.460467

[5 rows x 12 columns]
[2025-08-03T10:48:02.408+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-05-05', 'end_date': '2025-08-03'}
[2025-08-03T10:48:02.438+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250803T104700, start_date=20250803T104801, end_date=20250803T104802
[2025-08-03T10:48:02.505+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T10:48:02.539+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
