[2025-09-21T12:18:48.786+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:18:48.787+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:18:48.843+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:18:48.845+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:18:48.917+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T12:17:00+00:00 [queued]>
[2025-09-21T12:18:48.929+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T12:17:00+00:00 [queued]>
[2025-09-21T12:18:48.950+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T12:18:48.969+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 12:17:00+00:00
[2025-09-21T12:18:48.982+0000] {standard_task_runner.py:57} INFO - Started process 242 to run task
[2025-09-21T12:18:48.990+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T12:17:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpq8blbx_z']
[2025-09-21T12:18:48.997+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask validate_model_performance
[2025-09-21T12:18:49.082+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T12:18:49.083+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T12:17:00+00:00/task_id=validate_model_performance'
[2025-09-21T12:18:49.085+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T12:17:00+00:00 [running]> on host 1bfed80107dd
[2025-09-21T12:18:49.204+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T12:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T12:17:00+00:00'
[2025-09-21T12:18:49.245+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 863766.2578410085, 'rmse': 929.3902613224482, 'mae': 764.5428434673108, 'r2': 0.9101328049529867}
[2025-09-21T12:18:49.281+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T121700, start_date=20250921T121848, end_date=20250921T121849
[2025-09-21T12:18:49.322+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T12:18:49.347+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
