[2025-09-21T11:37:12.664+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:37:12.665+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:37:12.705+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:37:12.706+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:37:12.759+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:36:00+00:00 [queued]>
[2025-09-21T11:37:12.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:36:00+00:00 [queued]>
[2025-09-21T11:37:12.771+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:37:12.790+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): validate_model_performance> on 2025-09-21 11:36:00+00:00
[2025-09-21T11:37:12.800+0000] {standard_task_runner.py:57} INFO - Started process 1195 to run task
[2025-09-21T11:37:12.805+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'validate_model_performance', 'scheduled__2025-09-21T11:36:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmp66qpdvd0']
[2025-09-21T11:37:12.808+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask validate_model_performance
[2025-09-21T11:37:12.898+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509
[2025-09-21T11:37:12.900+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:36:00+00:00/task_id=validate_model_performance'
[2025-09-21T11:37:12.904+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.validate_model_performance scheduled__2025-09-21T11:36:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:37:13.026+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='validate_model_performance' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:36:00+00:00'
[2025-09-21T11:37:13.075+0000] {python.py:194} INFO - Done. Returned value was: {'mse': 1127166.9201491335, 'rmse': 1061.681176318547, 'mae': 855.2307692633735, 'r2': 0.9316938110111044}
[2025-09-21T11:37:13.108+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=validate_model_performance, execution_date=20250921T113600, start_date=20250921T113712, end_date=20250921T113713
[2025-09-21T11:37:13.177+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:37:13.200+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
