[2025-09-21T11:12:02.081+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:12:02.082+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:12:02.131+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:12:02.134+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:12:02.193+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:11:00+00:00 [queued]>
[2025-09-21T11:12:02.207+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:11:00+00:00 [queued]>
[2025-09-21T11:12:02.208+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-21T11:12:02.231+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_training_data> on 2025-09-21 11:11:00+00:00
[2025-09-21T11:12:02.244+0000] {standard_task_runner.py:57} INFO - Started process 416 to run task
[2025-09-21T11:12:02.251+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_predict_to_db', 'fetch_training_data', 'scheduled__2025-09-21T11:11:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/train_predict_to_db_dag.py', '--cfg-path', '/tmp/tmpk5_177yb']
[2025-09-21T11:12:02.257+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask fetch_training_data
[2025-09-21T11:12:02.362+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509
[2025-09-21T11:12:02.363+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=train_predict_to_db/run_id=scheduled__2025-09-21T11:11:00+00:00/task_id=fetch_training_data'
[2025-09-21T11:12:02.366+0000] {task_command.py:416} INFO - Running <TaskInstance: train_predict_to_db.fetch_training_data scheduled__2025-09-21T11:11:00+00:00 [running]> on host 36da5371e73d
[2025-09-21T11:12:02.542+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_predict_to_db' AIRFLOW_CTX_TASK_ID='fetch_training_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T11:11:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-21T11:11:00+00:00'
[2025-09-21T11:12:02.561+0000] {db_utils.py:17} INFO - Connected to PostgreSQL
[2025-09-21T11:12:04.302+0000] {train_predict_to_db_dag.py:29} INFO - Fetched training data tail:
            id  store  ...  productname                 created_at
100513  155953    454  ...    product_A 2025-09-21 11:11:14.274299
100514  155954    455  ...    product_A 2025-09-21 11:11:24.254101
100515  155955    456  ...    product_A 2025-09-21 11:11:35.200104
100516  155956    457  ...    product_A 2025-09-21 11:11:45.211269
100517  155957    458  ...    product_A 2025-09-21 11:11:55.224957

[5 rows x 12 columns]
[2025-09-21T11:12:04.383+0000] {python.py:194} INFO - Done. Returned value was: {'store': 370, 'start_date': '2025-06-23', 'end_date': '2025-09-21'}
[2025-09-21T11:12:04.464+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=train_predict_to_db, task_id=fetch_training_data, execution_date=20250921T111100, start_date=20250921T111202, end_date=20250921T111204
[2025-09-21T11:12:04.595+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-21T11:12:04.641+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
